### ISSUE TITLE
Admin inlines appear as editable on default form

### ISSUE THREAD

**Issue by jayvdb** [jyveapp/django-action-framework#13]
When running actions from the admin, and using the default template form , the `AdminModel.inlines` are shown allowing new inline entries to be created.

**Comment by 0x213F** [comment]
I'm having the same issue.

It looks like `daf/admin/action.html` inherits from [`change_form.html`](https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/change_form.html#L56) which brings inline field sets along.

If you put the following in `daf/admin/action.html` those inlines will go away.

```
{% block inline_field_sets %}
{% endblock %}
```

Perhaps the fix is as simple as that, but here are a couple things that come to mind:

1: Maybe there is a better way to write it?
2: Should there should be an option to keep the inlines? I'm thinking probably not.
3: Do any tests need to be added (maybe an inline admin?)

**Comment by jayvdb** [comment]
I found that I was getting errors when I only omitted them, so I've instead hidden them.
